Controllers/FlightController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using CourseWork.Models;
using CourseWork.Data;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using CourseWork.ViewModels;
using Microsoft.EntityFrameworkCore;

namespace CourseWork.Controllers;

public class FlightController : Controller
{
    private readonly ApplicationDbContext _context;
    public FlightController(ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult List()
    {
        var flights = _context.Flights.Where(f => f.DepartureDate > DateTime.Now).ToList();
        var flightsWithCount = new List<FlightWithCount>();
        foreach (var flight in flights)
        {
            int ticketCount = _context.Tickets.Count(t => t.FlightID == flight.ID && t.BookedBy == null);
            var flightWithCount = flight.ToFlightWithCount(ticketCount);
            flightsWithCount.Add(flightWithCount);
        }

        return View(flightsWithCount);
    }

    public IActionResult Details(Guid FlightId)
    {
        Flight flight = _context.Flights.FirstOrDefault(f => f.ID == FlightId);
        flight.Tickets = _context.Tickets.Where(t => t.FlightID == FlightId && t.BookedBy == null).ToList();

        string errorMessage = TempData["ErrorMessage"] as string;
        if (!string.IsNullOrEmpty(errorMessage))
        {
            ModelState.AddModelError(string.Empty, errorMessage);
        }
        return View(flight);
    }
    [HttpPost]
    [Authorize]
    public async Task<IActionResult> Payment(string id, string selectedSeatsInput)
    {
        if(selectedSeatsInput.Count() != 0 && selectedSeatsInput != null)
        {
            List<int> SelectedSeats = selectedSeatsInput.Split(',')
                         .Select(int.Parse)
                         .ToList();

            Flight flight = await _context.Flights
            .Include(f => f.Tickets)
            .SingleOrDefaultAsync(f => f.ID == Guid.Parse(id));
            FlightViewModel model = new(flight, SelectedSeats);
            if (flight.DepartureDate < DateTime.Now)
            {
                TempData["ErrorMessage"] = "Бронювання квитків на вже початий рейс недоступне";
                return RedirectToAction("Details", new { FlightId = Guid.Parse(id) });
            }
            foreach (Ticket ticket in flight.GetSelectedTickets(SelectedSeats))
            {
            if(ticket.BookedBy != null)
                {
                    TempData["ErrorMessage"] = "Деякі з обраних квитків вже були заброньовані";
                    return RedirectToAction("Details", new { FlightId = Guid.Parse(id) });
                }
            }
            return View(model);
        }
        TempData["ErrorMessage"] = "Оберіть хоча-б одне місце";
        return RedirectToAction("Details", new { FlightId = Guid.Parse(id) });
    }

    [HttpPost]
    [Authorize]
    public async Task<IActionResult> BookTickets(string id, List<int> selectedSeats)
    {
        if(User.Identity.IsAuthenticated)
        {
            Guid userId = Guid.Parse(HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType)?.Value);
            Flight flight = await _context.Flights
            .Include(f => f.Tickets)
            .SingleOrDefaultAsync(f => f.ID == Guid.Parse(id));

            foreach (Ticket ticket in flight.GetSelectedTickets(selectedSeats))
            {
                ticket.BookedBy = userId;
            }
            await _context.SaveChangesAsync();
            return RedirectToAction("Tickets", "Account");
        }
        return View(Details(Guid.Parse(id)));
    }
    [Authorize]
    public async Task SetTicketOwnerNull(int seat, Guid flightId)
    {
        Guid userId = Guid.Parse(HttpContext.User.FindFirst(ClaimsIdentity.DefaultNameClaimType)?.Value);
        Ticket ticket = await _context.Tickets
        .SingleOrDefaultAsync(t => t.Seat == seat && t.FlightID == flightId && t.BookedBy == userId);
        ticket.BookedBy = null;
        _context.SaveChanges();
    }
    [Authorize]
    public async Task<IActionResult> UnbookTicket(int seat, Guid flightId)
    {
        await SetTicketOwnerNull(seat, flightId);
        return RedirectToAction("Tickets", "Account");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TickNTrip</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CourseWork.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TickNTrip</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Index">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Flight"
                                asp-action="List">Забронювати</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Умови
                                використання</a>
                        </li>
                        @if(User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="FlightManagement">Керування рейсами</a>
                            </li>
                            if(User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="UserManagement">Керування користувачами</a>
                                </li>
                            }
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (!User.Identity.IsAuthenticated)
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Login">Увійти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Signup">Зареєструватися</a>
                        </li>
                        }
                        else
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Details">Особистий кабінет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Tickets">Мої квитки</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account"
                                asp-action="Logout">Вийти</a>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CourseWork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>